### ISSUE TITLE
AECOM-DS (v1.0): Conditions Data Annotation

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#11]
### Completion Checklist

- [x] Conditions Data Annotated
- [ ] Data handed off for Harmonization

### Additional Notes

Link: https://www.synapse.org/Synapse:syn62709462

**Comment by twhetzel** [comment]
I annotated the AECOM conditions, but I do not see an upload icon [here](https://www.synapse.org/Synapse:syn31872157/files/) to add the file back to Synapse. @lopierra do you know how I can upload the file?

**Comment by lopierra** [comment]
@twhetzel sorry, you should have upload access now - let me know if it's still not working.

**Comment by twhetzel** [comment]
Perfect! I was able to upload the file.

**Comment by a-l-holmes** [comment]
@twhetzel would you mind providing the link to the AECOM annotations in Synapse?

**Comment by twhetzel** [comment]
@a-l-holmes it is uploaded, but for no particular reason I uploaded the annotated file as an Excel file so there is not a preview of the file contents displayed on Synapse.
