### ISSUE TITLE
AECOM-DS (v1.0): Summary Generation

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#14]
### Relevant Data Types

- [x] Participant Data
- [x] Conditions Data
- [ ] Biospecimen Data

### Completion Checklist

- [x] Participants Data
- [x] Conditions Data
- [ ] Biospecimen Data

**Comment by a-l-holmes** [comment]
Summaries on synapse: https://www.synapse.org/Synapse:syn64421542
