### ISSUE TITLE
BrainPower (v1.1): Conditions Data Annotation

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#18]
### Completion Checklist

- [x] Conditions Data Annotated
- [ ] Data handed off for [Annotations Review](https://github.com/include-dcc/Data-Harmonization-and-QC-Team/issues/31)

**Comment by a-l-holmes** [comment]
@twhetzel files to annotate are noted in [this issue]( https://github.com/include-dcc/Data-Harmonization-and-QC-Team/issues/32) 🎊

**Comment by twhetzel** [comment]
The annotated file is at: https://www.synapse.org/Synapse:syn64320462

@JamedFV what is the second step, "Data handed off for Harmonization"?

**Comment by twhetzel** [comment]
Thanks @JamedFV and what is the "process" for handing the annotated data to Pierrette for review?

**Comment by JamedFV** [comment]
@twhetzel Not that it's a "hard-requirement", but I think following Ann's approach of adding the link to the annotated data to your ticket then going into the respective ticket, in this case for annotations review, and comment linking to the data and tagging the person would be good!
