### ISSUE TITLE
BrainPower (v1.1): Conditions Data Harmonization 

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#19]
### Completion Checklist

- [x] Conditions Data Harmonized
- [x] Data handed off for FHIR ingest

**Comment by twhetzel** [comment]
@a-l-holmes are you annotating BrainPower conditions?

If not, is the correct file the one [here](https://www.synapse.org/Synapse:syn62146210) named "Health Conditions.csv"?

**Comment by a-l-holmes** [comment]
Link to harmonized Brain Power Conditions data: https://www.synapse.org/Synapse:syn56389672
