### ISSUE TITLE
BrainPower (v1.1): Summary Generation

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#21]
### Relevant Data Types

- [x] Participant Data
- [x] Conditions Data
- [ ] Biospecimen Data

### Completion Checklist

- [x] Participants Data
- [x] Conditions Data
- [ ] Biospecimen Data

**Comment by a-l-holmes** [comment]
Link to summaries of BrainPower conditions and participants data: https://www.synapse.org/Synapse:syn64421542
