### ISSUE TITLE
TEAM-DS (v1.1): Conditions Data Harmonization 

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#23]
### Completion Checklist

- [x] Conditions Data Harmonized
- [x] Data handed off for FHIR ingest

**Comment by lopierra** [comment]
@JamedFV Harmonized & Validated TEAM-DS Conditions are [here](https://www.synapse.org/Synapse:syn57528143)

Updates since v5:
- added free-text conditions
- added height & weight 
- added Event ID = "Baseline" for Height, Weight, BMI (not for conditions that are "history of")
