### ISSUE TITLE
TEAM-DS (v1.1): Data Validation

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#24]
### Relevant Data Types

- [ ] Participant Data
- [x] Conditions Data
- [ ] Biospecimen Data

### Completion Checklist

- [ ] Participants Data Validation Passed
- [x] Conditions Data Validation Passed
- [ ] Biospecimen Data Validation Passed

**Comment by lopierra** [comment]
Used LinkML validator + manual spot checks against original data
