### ISSUE TITLE
TEAM-DS (v1.1): Summary Generation

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#25]
### Relevant Data Types

- [ ] Participant Data
- [x] Conditions Data
- [ ] Biospecimen Data

### Completion Checklist

- [ ] Participants Data
- [x] Conditions Data
- [ ] Biospecimen Data

**Comment by lopierra** [comment]
TEAM-DS Conditions summary: https://www.synapse.org/Synapse:syn64421545
