### ISSUE TITLE
TEAM-DS (v1.1): Conditions Annotations Review

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#28]
### Completion Checklist

- [x] Conditions Annotations Reviewed
- [x] Issues Addressed
- [x] Data handed off for Harmonization

**Comment by lopierra** [comment]
Annotated & reviewed conditions are in [this sheet](https://docs.google.com/spreadsheets/d/1cHSburUDg6CR4az5FZR82FI992h7cyv-22pLVTFLZvE/edit?gid=596309334#gid=596309334)
