### ISSUE TITLE
AECOM-DS (v1.0): Conditions Annotations Review

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#29]
### Completion Checklist

- [x] Conditions Annotations Reviewed
- [ ] Issues Addressed
- [x] Data handed off for Harmonization

**Comment by lopierra** [comment]
@a-l-holmes @twhetzel I reopened this since there is still one remaining question about "sinus" (see [Slack thread](https://teaminclude.slack.com/archives/C06USD10H2T/p1733967149589409)). Feel free to close when the issue is addressed.
