### ISSUE TITLE
BrainPower (v1.1): Conditions Annotations Review

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#31]
### Completion Checklist

- [x] Conditions Annotations Reviewed
- [ ] Issues Addressed
- [x] Data handed off for Harmonization

**Comment by lopierra** [comment]
@twhetzel @a-l-holmes the reviewed annotations are uploaded as a new version [here](https://www.synapse.org/Synapse:syn64320462). Notes:

- added a few missing terms
- NTR from MAxO: vascular surgery (row 15)
- added LOINC terms for measures
