### ISSUE TITLE
AECOM-DS (v1.0): Participants Data Harmonization

### ISSUE THREAD

**Issue by JamedFV** [include-dcc/Data-Harmonization-and-QC-Team#9]
### Data Received Certification

- [X] I certify all data has been processed and handed off from the Data Intake Team.

### Completion Checklist

- [X] Participant IDs Checked
- [X] Global IDs Minted
- [X] Data Harmonized

**Comment by a-l-holmes** [comment]
[File Location on Synapse](https://www.synapse.org/Synapse:syn64153341)
